apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace : {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: {{ .Values.backend.image }}
        name: backend-k8s
        resources: {}
        env:
         - name: MONGO_CONN_STR
           value: mongodb://mongodb:{{.Values.mongo.port }}
         - name: PORT
           value: {{.Values.backend.port | quote }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace : {{ .Values.namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: {{.Values.backend.port }}
  selector:
    app: backend
  type: ClusterIP

