apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace : {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: {{ .Values.frontend.image }}
        name: frontend-k8s
        env:
          - name: REACT_APP_BACKEND_URL
            value: http://backend:8080/api/tasks
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace : {{ .Values.namespace }}
spec:
  ports:
  - port: 3000
  selector:
    app: frontend
  type: LoadBalancer
