apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace : {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: mongo

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace : {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.mongo.port }}
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
