apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: docker.io/adityajoshi12/frontend-k8s:1.1
        name: frontend-k8s
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: http://a50b3022225834b69ae143da855dd9bf-1583827020.us-west-2.elb.amazonaws.com:8080/api/tasks
        
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port: 3000
  selector:
    app: frontend
  type: LoadBalancer