apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: docker.io/adityajoshi12/backend-k8s:1.1
        name: backend-k8s
        resources: {}
        env:
         - name: MONGO_CONN_STR
           value: mongodb://mongo:8080
         - name: PORT
           value: "80"
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: backend
  type: ClusterIP