apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: 
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "" #$API_ELB_PUBLIC_FQDN #add your API_Load_Balancer DNS manually here if app does not run
        ports:
        - containerPort: 3000
